### ISSUE TITLE
trying to understand use cases & a feature request

### ISSUE THREAD

**Issue by anandkumar89** [rpapallas/illustrate.nvim#1]
It's pretty clear why I'd use `create_and_open`. But use case of rest two of functions aren't much clear to me 
- `open_under_cursor` : maybe useful when re-editing the image. 
- `search_and_open` : don't know how to use this, probably same as re-editing the image. Instead

`search_and_open` would have been useful if would be able to duplicate the figure and create a new figure. Not sure if telescope supports some callback i.e. the selected figure copied to new path and opened in inkscape; code for figure is either inserted or copied for pasting when a particular key-combination is pressed in picker. 

I've tried to replicate your code for my use case - I use `inkscape` to create figures. `nvim` with `plug`. Did spend fair bit of time figuring out how to make it work - new to entire ecosystem. I did remove all `ai` related code, and refactored it to create a figure directory as sibling to open file.

**Comment by rpapallas** [comment]
Hello,

Thanks for sharing your thoughts. I would usually write LaTeX documents or presentations with Beamer and sometimes, as I iterate over the documents I need to open a particular figure to edit. I found that most of the times, the most convenient way is to get my cursor under the figure I want to edit, and then hit `<leader>io` to open it and edit. The other way is to just search through the illustrations to open and edit. These are meant for when you want to edit an illustration.

Making a copy of a particular illustration is an interesting idea and I can look into implementing it! I do find myself lately going to the terminal to copy an svg to another one.

What's your use case? 

Are you using vimplug as your plugin manager? If so, I am happy to look into supporting it. A little busy this week, but I can look into it this weekend.

**Comment by anandkumar89** [comment]
yes, I use vimplug as plugin manager - worked with only minor refactoring. 

I think I would mostly want two things - (i) create a new blank figure with set dimensions, (ii) create a new figure that is similar to some old figure (selected via picker). I do like the idea of previewing already available figures - but pickers have keybindings - that both functionalities probably could be mapped to different keybindings. 

---

I think I understand how it can be done : instead of calling `utils.open(selection.value)`, need to call `create_and_open_svg(selection.value)` where `selection.value` is path of the file selected (assuming). 

this selection.value is then used to create the new file : copy `selection.value` to `figures/[input].svg` instead of calling `create_document` or refactor `create_document` to allow overriding using `default` value. 

I guess this is it - would allow reusing code.

**Comment by rpapallas** [comment]
Thanks, can you share the modifications for running this with vimplug? If trivial, I may be able to push an implementation sooner for vimplug.

Regarding dimensions, how often do you need new dimensions? I was thinking initially of having a list of “templates” SVGs (you can choose the dimensions there) and then illustrate.nvim in the future would allow you to create a new SVG from a selected template. So if you tend to have 3-4 different dimensions for your SVGs you will have 3–4 templates and then on creation you will pick one. Another solution would be to define dimensions from neovim and create a new SVG from them, although this may be a little tricky to implement (and not sure if actually most people would need novel dimensions for new figures, I feel most people will have 3-4 templates they want to alternate).

**Comment by anandkumar89** [comment]
I don't need new dimensions most often, when I do, itf be possible to resize on the fly inside inkscape. 

I suggested reusing old illustrations to create new one - because sometimes some components of old figure can be reused. Nothing more. It's not a super frequent use case but something gill castel had in his workflow.

**Comment by anandkumar89** [comment]
have uploaded, but since I've somehow just made it work - I should not submit a pull request. but still, you can take a look here - https://github.com/anandkumar89/illustrate.nvim

**Comment by rpapallas** [comment]
Hello @anandkumar89,

I have a working version of the copy-and-open functionality, as well as changes to get the plugin working with vim-plug out of the box. 

Can I ask if you could give it a test to see if it works on your end? You can find instructions of [how to install it with vim-plug in the readme file](https://github.com/rpapallas/illustrate.nvim?tab=readme-ov-file#vim-plug). 

Also note the new function `illustrate_finder.search_create_copy_and_open` which will first open search to find an existing file to copy, then it will ask for a new name, and then it will open the new copy in the default app. 

It will be good to test this with my copy using `'rpapallas/illustrate.nvim'` to see if it will work out of the box, as show below:

```lua
local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
    Plug 'rpapallas/illustrate.nvim'
    Plug 'rcarriga/nvim-notify'
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim'
vim.call('plug#end')

local illustrate = require('illustrate')
local illustrate_finder = require('illustrate.finder')
vim.keymap.set('n', '<leader>is', function() illustrate.create_and_open_svg() end, {})
vim.keymap.set('n', '<leader>ia', function() illustrate.create_and_open_ai() end, {})
vim.keymap.set('n', '<leader>io', function() illustrate.open_under_cursor() end, {})
vim.keymap.set('n', '<leader>if', function() illustrate_finder.search_and_open() end, {})
vim.keymap.set('n', '<leader>ic', function() illustrate_finder.search_create_copy_and_open() end, {})
```

Thanks!

**Comment by anandkumar89** [comment]
figure is being created one directory above. thus can't include using `\includesvg{figures\fig.svg}`

I think plugin assumes that latex file where code is inserted is in `pwd`. But this need not be case always (I edit chapters - which live in separate chapters folders). there could be two approaches - 
1. create figure directory on same level as current tex file.
2. get the (relative) path of figure created from current tex file and insert it in the code.

While second option leads to more manageable project - all figures in same directory; first option is easy to implement.

**Comment by rpapallas** [comment]
Interesting, that's a good catch. I will look into this.

Did you have success with using the new changes and vimplug out-of-the-box with the latest changes (if working with a file in cwd)?

**Comment by anandkumar89** [comment]
yes, it does work. Opens telescope, creates a clone of selected file and inserts the code. Installation was smooth. thanks for make it work. I too need to go through the code.

**Comment by rpapallas** [comment]
Thanks for helping with testing. I created a new issue for the relative paths: https://github.com/rpapallas/illustrate.nvim/issues/3

I am closing this one since it is now done.
