### ISSUE TITLE
Handling relative paths better

### ISSUE THREAD

**Issue by rpapallas** [rpapallas/illustrate.nvim#3]
Currently, code inserted into the document assumes that `figures` directory exists in the `cwd`. This may not work when working with files in subdirectories. 

This was first reported [here](https://github.com/rpapallas/illustrate.nvim/issues/1#issuecomment-2020105227).

**Comment by rpapallas** [comment]
@anandkumar89 just so I understand exactly the use case, can you provide a detailed set up of what the issue is with relative paths?

You have something like this:

```
├── chapters
│   ├── chapter1.tex
│   └── chapter2.tex
└── main.tex
```

You are now editting chapter1.tex while your cwd is chapters and you want the `figures` dir to be created in root directory or chapters?

**Comment by anandkumar89** [comment]
I usually keep all my figures in project root directory. However determining project root (aka main file for multi-file latex document) directory is non-trivial task - vimtex does this with few set of rules. The problem doesn't end there - after that relative path of figure from current buffer is to be found - seems much task for little gain. 

Second option: If current buffer is chapters/chapter1.tex then
```
├── chapters
│   ├── chapter1.tex
│   └── chapter2.tex
│   └── figures/fig.svg
└── main.tex
```
this is easier solution to the problem,`vim.fn.expand` could provide path of `chapters` directory. which then can be used in all copy and/or create commands.

**Comment by rpapallas** [comment]
I just pushed some improvements on how the plugin works to handle better cases like this.

I created a few examples to explain how it works [here](https://github.com/rpapallas/illustrate.nvim/tree/master/examples).

If you can, please update the plugin, have a read to the examples and let me know if this now handles your case.

**Comment by anandkumar89** [comment]
I updated the plugins. Currently working in single file setup. just the `pwd` is not same as working directory. this is my current setup.

```
├── All projects (pwd)
│   ├── projectA
│   │   └── mainfileA.tex (open buffer)
│   │   └── expectedfigDir
│   └── projectB
│   └── ::createdfigDir::
```

**Comment by rpapallas** [comment]
Yes this a challenging case to handle because it's not clear where the root dir is. However, if you manually create a figures dir inside those project directories it should work.

**Comment by anandkumar89** [comment]
the cases mentioned in example/readme works fine. I think it works mostly as expected enough to mark this issue closed.

**Comment by anandkumar89** [comment]
just asked @lervag. here's his response. In case you're using vimtex, it can be used to determine main file. Since vimtex works and is tried and tested on complicated projects, this would be somewhat fool proof solution - 

```
root_folder  = vim.fn.fnamemodify(vim.b.vimtex.tex, ":h")
```

https://github.com/lervag/vimtex/issues/2911#issuecomment-2035605757

**Comment by rpapallas** [comment]
@anandkumar89  thank you for this! This is now implemented: https://github.com/rpapallas/illustrate.nvim/commit/fabfd498ddc351d3129c9a8f10da24ce5c16badd

Please let me know if this now works as expected.

**Comment by lervag** [comment]
Hey; I looked at your patch here. It seems you want to use the root path. That is available as `vim.b.vimtex.root`, so you don't need to fnamemodify it yourself.

**Comment by rpapallas** [comment]
Thank you, @lervag. I will make use of the suggested variable. Great work with vimtex, by the way; I use it all the time 🙂.

**Comment by lervag** [comment]
Thanks for the kind words! :)
