### ISSUE TITLE
`open_under_cursor` not work

### ISSUE THREAD

**Issue by Fireond** [rpapallas/illustrate.nvim#6]
When using function `illustrate.open_under_cursor()`, report errors:
```
E5108: Error executing lua: .../share/nvim/lazy/illustrate.nvim/lua/illustrate/init.lua:71: attempt to concatenate local 'illustration_dir' (a nil value)
stack traceback:
	.../share/nvim/lazy/illustrate.nvim/lua/illustrate/init.lua:71: in function 'open_under_cursor'
	/home/fireond/.config/nvim/lua/plugins/write/latex.lua:110: in function </home/fireond/.config/nvim/lua/plugins/write/latex.lua:109>
```
It seems it cannot detect the 'illustration_dir', but `illustrate.create_and_open_ai()` can successfully create files in `figures/name.svg`, and can successfully add the svg file. Is anything I can try to fix this bug? Thanks!

Environments:
- NVIM v0.10.3
- LazyVim 14.6.0
- 6.12.6-arch1-1

**Comment by rpapallas** [comment]
Hello,

Thank you for using the plugin. Can you please provide your configuration of the plugin as well? I will have a look later and let you know.

**Comment by Fireond** [comment]
I just use the config provided in README:
```
return {
'rpapallas/illustrate.nvim',
dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-telescope/telescope.nvim',
},
keys = function()
    local illustrate = require('illustrate')
    local illustrate_finder = require('illustrate.finder')

    return {
        {
            "<leader>is",
            function() illustrate.create_and_open_svg() end,
            desc = "Create and open a new SVG file with provided name."
        },
        {
            "<leader>ia",
            function() illustrate.create_and_open_ai() end,
            desc = "Create and open a new Adobe Illustrator file with provided name."
        },
        {
            "<leader>io",
            function() illustrate.open_under_cursor() end,
            desc = "Open file under cursor (or file within environment under cursor)."
        },
        {
            "<leader>if",
            function() illustrate_finder.search_and_open() end,
            desc = "Use telescope to search and open illustrations in default app."
        },
        {
            "<leader>ic",
            function() illustrate_finder.search_create_copy_and_open() end,
            desc = "Use telescope to search existing file, copy it with new name, and open it in default app."
        },
    }
end,
opts = {
    -- optionally define options.
},
}
```
Nothing changes. Also `search_and_open()` and `search_create_copy_and_open()` do not work too, I think they have same reason.

**Comment by Fireond** [comment]
I found where the bug is: in `illustrate.utils:37`, for detecting the directory, you add twice `directory_name`. But after I modified this, when calling the function, it now has no errors but also no responses, and the file does not open.

**Comment by rpapallas** [comment]
@Fireond it looks like you are trying to open a figure that can't be found in the right place. It looks like the "illustration dir" doesn't exist where it's expected. Does the figure exist in the right place?

I suggest that you try first: `<leader>is` to create a new figure. This will also create the illustration directory in the right place. Then you try to open it using the under cursor command: `<leader>io`.

**Comment by rpapallas** [comment]
@Fireond you can also see examples of how to use the plugin [here](https://github.com/rpapallas/illustrate.nvim/tree/master/examples).

Please let me know if this is now fixed/working for you.

**Comment by Fireond** [comment]
Yes, it now works well!
